# Generated by Django 5.0.1 on 2024-02-06 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCategorie', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreConseil', models.CharField(max_length=255)),
                ('descriptionConseil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPatient', models.CharField(max_length=255)),
                ('agePatient', models.PositiveIntegerField()),
                ('phonePatient', models.CharField(max_length=20)),
                ('desciptionProblem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomLivreure', models.CharField(max_length=100)),
                ('phoneLivreure', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPorduit', models.CharField(max_length=255)),
                ('prixProduit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField()),
                ('descirpion', models.TextField()),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=255)),
                ('phoneClient', models.CharField(max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('isLivrer', models.BooleanField(default=False)),
                ('dateVente', models.DateTimeField()),
                ('Produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.produit')),
                ('livraison_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.livraison')),
            ],
        ),
    ]
