# Generated by Django 5.0.1 on 2024-02-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='nomPorduit',
            new_name='nomProduit',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='Produit',
            new_name='produit',
        ),
    ]
