# Generated by Django 5.0.1 on 2024-02-11 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produit_photoproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='poidPaient',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vente',
            name='livraison_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.livraison'),
        ),
    ]
