# Generated by Django 5.0.1 on 2024-02-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_consultation_poidpaient_alter_vente_livraison_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='codevente',
            field=models.CharField(null=True),
        ),
    ]
